CREATE TABLE AGENDAMENTO
(
    ID_AGENDAMENTO   INT AUTO_INCREMENT PRIMARY KEY,
    CD_CONTA_ORIGEM  VARCHAR(20)    NOT NULL,
    CD_CONTA_DESTINO VARCHAR(20)    NOT NULL,
    VL_TRANSFERENCIA DECIMAL(10, 2) NOT NULL,
    VL_TAXA          DECIMAL(10, 2),
    DT_AGENDAMENTO   DATE           NOT NULL, -- Data onde foi realizado o agendamento da transfêrencia
    DT_TRANSFERENCIA DATE           NOT NULL  -- Data onde a transferência deve ser realizada
);

CREATE TABLE TAXA_TRANSFERENCIA
(
    ID_TAXA       INT AUTO_INCREMENT PRIMARY KEY,
    DIA_INICIO    INT NOT NULL,
    DIA_FIM       INT NOT NULL,
    VL_FIXO       DECIMAL(10, 2),
    VL_PERCENTUAL DECIMAL(5, 2)
);